### ISSUE TITLE
Bug in world chat project

### ISSUE THREAD

**Issue by pruthvirajjadhav1** [FranciscanLads/franciscanlads.github.io#35]
[https://ankur-srivastava-1.github.io/Chat/temp.html](url)
 So I had found two bugs in this project.
1. Every time I enter it asks me "Enter Your Name:" it needs to be fixed.
2. Every time i write a messege in world chat it shifts my curser the second line.   

> I would like to work with you all please help me how can i catch up with you.

**Comment by ItsTimeToGetOut** [comment]
sorry bhai aaj dekha
